apiVersion: v1
kind: ConfigMap
metadata:
  name: cls-controller-config
  namespace: cls-system
  labels:
    app.kubernetes.io/name: cls-controller
    app.kubernetes.io/component: controller
data:
  config.yaml: |
    # CLS Controller Configuration for GKE deployment
    controller_name: "echo-test"
    project_id: "apahim-dev-1"

    # CLS-Backend API configuration (internal Kubernetes service)
    api_base_url: "http://cls-backend.cls-system:80/api/v1"
    api_timeout: "30s"

    # Organization configuration (domain-based with auto-mapping)
    organization_domain: "apahim-dev-1.com"
    auto_map_organization: true

    # Pub/Sub configuration for GCP (events only - status via API)
    events_subscription: "cls-controller-cluster-events"

    # Controller configuration
    config_namespace: "cls-system"
    config_name: "echo-test"

    # Kubernetes controller settings
    enable_leader_election: true
    metrics_addr: ":8080"
    probe_addr: ":8081"

    # Operational settings
    retry_attempts: 3
    retry_backoff: "5s"
    health_check_interval: "60s"
    template_timeout: "30s"