---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cls-hypershift-client
  namespace: cls-system
  labels:
    app.kubernetes.io/name: cls-hypershift-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cls-hypershift-client
  labels:
    app.kubernetes.io/name: cls-hypershift-client
rules:
- apiGroups:
  - cls.redhat.com
  resources:
  - controllerconfigs
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - cls.redhat.com
  resources:
  - controllerconfigs/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list
    - watch
    - update
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cls-hypershift-client
  labels:
    app.kubernetes.io/name: cls-hypershift-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cls-hypershift-client
subjects:
- kind: ServiceAccount
  name: cls-hypershift-client
  namespace: cls-system