# Simple configuration for testing the echo-test controller
controller_name: "echo-test"
project_id: "test-project"
api_base_url: "http://localhost:8080"
config_namespace: "cls-system"
config_name: "echo-test"

# Use emulator for local testing
pubsub_emulator_host: "localhost:8085"
status_topic: "cls-controller-status"
events_subscription: "cls-echo-test-events"

# Disable leader election for single instance testing
enable_leader_election: false
metrics_addr: ":8080"
probe_addr: ":8081"