# Config Connector resources to replace gcloud commands for cls-hypershift-client

---
# IAM Service Account
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ .Values.serviceAccount.gcp }}
  namespace: {{ .Values.controller.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.controller.name }}
    app.kubernetes.io/component: service-account
spec:
  displayName: "CLS Controller - {{ .Values.controller.name }}"
  description: "Service account for {{ .Values.controller.name }} controller to access GCP resources"
  resourceID: {{ .Values.serviceAccount.gcp }}

---
# Pub/Sub Subscription
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: {{ .Values.pubsub.subscription }}
  namespace: {{ .Values.controller.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.controller.name }}
    app.kubernetes.io/component: pubsub-subscription
spec:
  resourceID: {{ .Values.pubsub.subscription }}
  topicRef:
    external: "projects/{{ .Values.gcp.projectId }}/topics/{{ .Values.pubsub.topic }}"
  ackDeadlineSeconds: 60
  messageRetentionDuration: "604800s"  # 7 days
  enableMessageOrdering: false

---
# Pub/Sub IAM Policy Member
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ .Values.controller.name }}-pubsub-subscriber
  namespace: {{ .Values.controller.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.controller.name }}
    app.kubernetes.io/component: iam-policy
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubSubscription
    name: {{ .Values.pubsub.subscription }}
  role: "roles/pubsub.subscriber"
  memberFrom:
    serviceAccountRef:
      name: {{ .Values.serviceAccount.gcp }}

---
# Workload Identity IAM Policy Member
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ .Values.controller.name }}-workload-identity
  namespace: {{ .Values.controller.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.controller.name }}
    app.kubernetes.io/component: iam-policy
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ .Values.serviceAccount.gcp }}
  role: "roles/iam.workloadIdentityUser"
  member: "serviceAccount:{{ .Values.gcp.projectId }}.svc.id.goog[{{ .Values.controller.namespace }}/{{ .Values.serviceAccount.kubernetes }}]"