---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.kubernetes }}
  namespace: {{ .Values.controller.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.controller.name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcp }}@{{ .Values.gcp.projectId }}.iam.gserviceaccount.com

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.controller.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.controller.name }}
rules:
- apiGroups:
  - cls.redhat.com
  resources:
  - controllerconfigs
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - cls.redhat.com
  resources:
  - controllerconfigs/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list
    - watch
    - update
    - patch

---
# TODO: this should probbaly rather be a RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.controller.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.controller.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.controller.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.kubernetes }}
  namespace: {{ .Values.controller.namespace }}
