apiVersion: cls.redhat.com/v1alpha1
kind: ControllerConfig
metadata:
  name: hypershift-dns-subzone
  namespace: cls-system
spec:
  name: "hypershift-dns-subzone"
  description: "Creates DNS sub-zones for HyperShift cluster delegation using Config Connector"

  # Only process HyperShift clusters that need DNS sub-zones
  preconditions:
    - field: "spec.provider"
      operator: "eq"
      value: "gcp"
    - field: "spec.infrastructure_type"
      operator: "eq"
      value: "hypershift"
    - field: "spec.dns_management_enabled"
      operator: "eq"
      value: true
    - field: "spec.parent_dns_zone"
      operator: "exists"

  resources:
    - name: "dns-subzone"
      description: "Delegated DNS sub-zone for HyperShift cluster"
      resourceManagement:
        updateStrategy: "in_place"  # Config Connector resources are mutable
      template: |
        apiVersion: dns.cnrm.cloud.google.com/v1beta1
        kind: DNSManagedZone
        metadata:
          name: "{{.cluster.name}}-{{randomString 4}}-subzone"
          namespace: "{{.cluster.organization_domain | default "cls-system"}}"
          labels:
            cluster-id: "{{.cluster.id}}"
            cluster-generation: "{{.cluster.generation}}"
            controller: "hypershift-dns-subzone"
            cluster-name: "{{.cluster.name}}"
          annotations:
            cnrm.cloud.google.com/project-id: "{{.cluster.spec.gcp_project}}"
            cnrm.cloud.google.com/deletion-policy: "abandon"  # Keep DNS sub-zone if resource is deleted
        spec:
          # Create delegated DNS sub-zone for HyperShift operator
          dnsName: "{{randomString 4}}.{{.cluster.spec.base_domain}}."
          description: "Delegated DNS sub-zone for HyperShift cluster {{.cluster.name}}"
          visibility: "public"

  statusConditions:
    - name: "Applied"
      status: |
        {{- $zone := .resources.dns-subzone -}}
        {{- if $zone -}}
          {{- if $zone.metadata.name -}}True{{- else -}}False{{- end -}}
        {{- else -}}False{{- end -}}
      reason: |
        {{- $zone := .resources.dns-subzone -}}
        {{- if $zone -}}
          {{- if $zone.metadata.name -}}DNSManagedZoneCreated{{- else -}}DNSManagedZoneNotCreated{{- end -}}
        {{- else -}}DNSManagedZoneNotCreated{{- end -}}
      message: |
        {{- $zone := .resources.dns-subzone -}}
        {{- if $zone -}}
          {{- if $zone.metadata.name -}}DNS sub-zone {{ $zone.spec.dnsName }} has been created{{- else -}}DNS sub-zone has not been created yet{{- end -}}
        {{- else -}}DNS sub-zone has not been created yet{{- end -}}

    - name: "Available"
      status: |
        {{- $zone := .resources.dns-subzone -}}
        {{- if $zone -}}
          {{- if $zone.status -}}
            {{- if $zone.status.conditions -}}
              {{- range $zone.status.conditions -}}
                {{- if eq .type "Ready" -}}{{ .status }}{{- end -}}
              {{- end -}}
            {{- else -}}Unknown{{- end -}}
          {{- else -}}Unknown{{- end -}}
        {{- else -}}Unknown{{- end -}}
      reason: |
        {{- $zone := .resources.dns-subzone -}}
        {{- if $zone -}}
          {{- if $zone.status -}}
            {{- if $zone.status.conditions -}}
              {{- range $zone.status.conditions -}}
                {{- if eq .type "Ready" -}}
                  {{- if eq .status "True" -}}DNSZoneReady{{- else -}}DNSZoneNotReady{{- end -}}
                {{- end -}}
              {{- end -}}
            {{- else -}}DNSZonePending{{- end -}}
          {{- else -}}DNSZonePending{{- end -}}
        {{- else -}}DNSZonePending{{- end -}}
      message: |
        {{- $zone := .resources.dns-subzone -}}
        {{- if $zone -}}
          {{- if $zone.spec.dnsName -}}
            DNS sub-zone {{ $zone.spec.dnsName }}
            {{- if $zone.status -}}
              {{- if $zone.status.conditions -}}
                {{- range $zone.status.conditions -}}
                  {{- if eq .type "Ready" -}}
                    {{- if eq .status "True" -}} is available for HyperShift delegation{{- else -}} {{ .message }}{{- end -}}
                  {{- end -}}
                {{- end -}}
              {{- else -}} availability is being determined{{- end -}}
            {{- else -}} availability is being determined{{- end -}}
          {{- else -}}DNS sub-zone availability is being determined{{- end -}}
        {{- else -}}DNS sub-zone availability is being determined{{- end -}}

    - name: "Ready"
      status: |
        {{- $zone := .resources.dns-subzone -}}
        {{- if $zone -}}
          {{- if $zone.status -}}
            {{- if $zone.status.observedGeneration -}}
              {{- if eq $zone.metadata.generation $zone.status.observedGeneration -}}True{{- else -}}False{{- end -}}
            {{- else -}}Unknown{{- end -}}
          {{- else -}}Unknown{{- end -}}
        {{- else -}}Unknown{{- end -}}
      reason: |
        {{- $zone := .resources.dns-subzone -}}
        {{- if $zone -}}
          {{- if $zone.status -}}
            {{- if $zone.status.observedGeneration -}}
              {{- if eq $zone.metadata.generation $zone.status.observedGeneration -}}DNSZoneSynced{{- else -}}DNSZoneOutOfSync{{- end -}}
            {{- else -}}DNSZoneSyncPending{{- end -}}
          {{- else -}}DNSZoneSyncPending{{- end -}}
        {{- else -}}DNSZoneSyncPending{{- end -}}
      message: |
        {{- $zone := .resources.dns-subzone -}}
        {{- if $zone -}}
          {{- if $zone.spec.dnsName -}}
            DNS sub-zone {{ $zone.spec.dnsName }}
            {{- if $zone.status -}}
              {{- if $zone.status.observedGeneration -}}
                {{- if eq $zone.metadata.generation $zone.status.observedGeneration -}} is ready and in sync with desired state{{- else -}} is being updated to match desired state{{- end -}}
              {{- else -}} sync status is unknown{{- end -}}
            {{- else -}} sync status is unknown{{- end -}}
          {{- else -}}DNS sub-zone sync status is unknown{{- end -}}
        {{- else -}}DNS sub-zone sync status is unknown{{- end -}}