apiVersion: cls.redhat.com/v1alpha1
kind: ControllerConfig
metadata:
  name: echo-test
  namespace: cls-system
spec:
  name: "echo-test"
  description: "Simple echo job for testing the generalized controller"
  resources:
    - name: "echo-job"
      description: "Simple job that echoes cluster information"
      resourceManagement:
        updateStrategy: "versioned"  # Required for Jobs (immutable resources)
        newGenerationOnly: true      # Only recreate on generation changes
        keepVersions: 2              # Keep 2 completed versions for history
      template: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: "echo-{{.cluster.id}}-gen-{{.cluster.generation}}-{{.timestamp}}"
          namespace: "default"
          labels:
            cluster-id: "{{.cluster.id}}"
            cluster-generation: "{{.cluster.generation}}"
            controller: "echo-test"
            test-job: "true"
        spec:
          template:
            spec:
              containers:
              - name: echo
                image: "busybox:1.35"
                command: ["/bin/sh"]
                args:
                  - -c
                  - |
                    echo "=== CLS Controller Echo Test ==="
                    echo "Cluster ID: {{.cluster.id}}"
                    echo "Cluster Name: {{.cluster.name}}"
                    echo "Cluster Generation: {{.cluster.generation}}"
                    echo "Timestamp: {{.timestamp}}"
                    echo "Random String: {{randomString 8}}"
                    echo "Controller: {{.controller.name}}"
                    {{- if .cluster.spec}}
                    echo "Cluster Spec: {{toJson .cluster.spec}}"
                    {{- end}}
                    echo "=== Job Completed Successfully ==="
                    sleep 5
              restartPolicy: Never
          backoffLimit: 1
          activeDeadlineSeconds: 60

  statusConditions:
    - name: "Applied"
      status: |
        {{- $job := index .resources "echo-job" -}}
        {{- if $job -}}
          {{- if $job.metadata.name -}}True{{- else -}}False{{- end -}}
        {{- else -}}False{{- end -}}
      reason: |
        {{- $job := index .resources "echo-job" -}}
        {{- if $job -}}
          {{- if $job.metadata.name -}}EchoJobCreated{{- else -}}EchoJobNotCreated{{- end -}}
        {{- else -}}EchoJobNotCreated{{- end -}}
      message: |
        {{- $job := index .resources "echo-job" -}}
        {{- if $job -}}
          {{- if $job.metadata.name -}}Echo job {{ $job.metadata.name }} has been created{{- else -}}Echo job has not been created yet{{- end -}}
        {{- else -}}Echo job has not been created yet{{- end -}}

    - name: "Available"
      status: |
        {{- $job := index .resources "echo-job" -}}
        {{- $complete := false -}}
        {{- $failed := false -}}
        {{- $running := false -}}
        {{- if $job -}}
          {{- if $job.status -}}
            {{- if $job.status.conditions -}}
              {{- range $job.status.conditions -}}
                {{- if eq .type "Complete" -}}
                  {{- if eq .status "True" -}}{{$complete = true}}{{- end -}}
                {{- else if eq .type "Failed" -}}
                  {{- if eq .status "True" -}}{{$failed = true}}{{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}
            {{- if $job.status.active -}}
              {{- if gt $job.status.active 0 -}}{{$running = true}}{{- end -}}
            {{- end -}}
          {{- end -}}
        {{- end -}}
        {{- if $complete -}}True{{- else if $failed -}}False{{- else if $running -}}Unknown{{- else -}}Unknown{{- end -}}
      reason: |
        {{- $job := index .resources "echo-job" -}}
        {{- $complete := false -}}
        {{- $failed := false -}}
        {{- $running := false -}}
        {{- if $job -}}
          {{- if $job.status -}}
            {{- if $job.status.conditions -}}
              {{- range $job.status.conditions -}}
                {{- if eq .type "Complete" -}}
                  {{- if eq .status "True" -}}{{$complete = true}}{{- end -}}
                {{- else if eq .type "Failed" -}}
                  {{- if eq .status "True" -}}{{$failed = true}}{{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}
            {{- if $job.status.active -}}
              {{- if gt $job.status.active 0 -}}{{$running = true}}{{- end -}}
            {{- end -}}
          {{- end -}}
        {{- end -}}
        {{- if $complete -}}JobCompleted{{- else if $failed -}}JobFailed{{- else if $running -}}JobRunning{{- else -}}JobPending{{- end -}}
      message: |
        {{- $job := index .resources "echo-job" -}}
        {{- $complete := false -}}
        {{- $failed := false -}}
        {{- $running := false -}}
        {{- if $job -}}
          {{- if $job.status -}}
            {{- if $job.status.conditions -}}
              {{- range $job.status.conditions -}}
                {{- if eq .type "Complete" -}}
                  {{- if eq .status "True" -}}{{$complete = true}}{{- end -}}
                {{- else if eq .type "Failed" -}}
                  {{- if eq .status "True" -}}{{$failed = true}}{{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}
            {{- if $job.status.active -}}
              {{- if gt $job.status.active 0 -}}{{$running = true}}{{- end -}}
            {{- end -}}
          {{- end -}}
        {{- end -}}
        Echo job {{- if $complete -}} completed successfully{{- else if $failed -}} failed{{- else if $running -}} is running with {{ $job.status.active }} active pods{{- else -}} is pending{{- end -}}

    - name: "Ready"
      status: |
        {{- $job := index .resources "echo-job" -}}
        {{- if $job -}}
          {{- if $job.metadata.generation -}}True{{- else -}}Unknown{{- end -}}
        {{- else -}}Unknown{{- end -}}
      reason: |
        {{- $job := index .resources "echo-job" -}}
        {{- if $job -}}
          {{- if $job.metadata.generation -}}JobCreated{{- else -}}JobPending{{- end -}}
        {{- else -}}JobPending{{- end -}}
      message: |
        {{- $job := index .resources "echo-job" -}}
        {{- if $job -}}
          {{- if $job.metadata.generation -}}Echo job has been created and is being processed{{- else -}}Echo job is being created{{- end -}}
        {{- else -}}Echo job is being created{{- end -}}