apiVersion: cls.redhat.com/v1alpha1
kind: ControllerConfig
metadata:
  name: gcp-environment-validation
  namespace: cls-system
spec:
  name: "gcp-environment-validation"
  description: "Validates GCP environment before cluster creation"

  # Only process GCP clusters
  preconditions:
    - field: "spec.provider"
      operator: "eq"
      value: "gcp"

  resources:
    - name: "validation-job"
      description: "GCP environment validation job"
      resourceManagement:
        updateStrategy: "versioned"  # Required for Jobs (immutable resources)
        versionInterval: "5m"        # Wait 5 minutes before recreating completed jobs
        newGenerationOnly: false     # Allow time-based recreation within same generation
        keepVersions: 3              # Keep 3 validation results
      template: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: "gcp-validate-{{.cluster.id}}-gen-{{.cluster.generation}}-{{.timestamp}}"
          namespace: "cls-system"
          labels:
            cluster-id: "{{.cluster.id}}"
            cluster-generation: "{{.cluster.generation}}"
            controller: "gcp-environment-validation"
        spec:
          template:
            spec:
              containers:
              - name: validator
                image: "gcr.io/my-project/gcp-validator:latest"
                env:
                - name: CLUSTER_ID
                  value: "{{.cluster.id}}"
                - name: GCP_PROJECT
                  value: "{{.cluster.spec.gcp_project}}"
                - name: GCP_REGION
                  value: "{{.cluster.spec.region}}"
                volumeMounts:
                - name: gcp-key
                  mountPath: /etc/gcp
                  readOnly: true
              volumes:
              - name: gcp-key
                secret:
                  secretName: gcp-service-account-key
              restartPolicy: Never
          backoffLimit: 2
          activeDeadlineSeconds: 300

  statusConditions:
    - name: "Applied"
      status: |
        {{- $job := .resources.validation-job -}}
        {{- if $job -}}
          {{- if $job.metadata.name -}}True{{- else -}}False{{- end -}}
        {{- else -}}False{{- end -}}
      reason: |
        {{- $job := .resources.validation-job -}}
        {{- if $job -}}
          {{- if $job.metadata.name -}}ValidationJobCreated{{- else -}}ValidationJobNotCreated{{- end -}}
        {{- else -}}ValidationJobNotCreated{{- end -}}
      message: |
        {{- $job := .resources.validation-job -}}
        {{- if $job -}}
          {{- if $job.metadata.name -}}GCP validation job {{ $job.metadata.name }} has been created{{- else -}}GCP validation job has not been created yet{{- end -}}
        {{- else -}}GCP validation job has not been created yet{{- end -}}

    - name: "Available"
      status: |
        {{- $job := .resources.validation-job -}}
        {{- $complete := false -}}
        {{- $failed := false -}}
        {{- if $job -}}
          {{- if $job.status -}}
            {{- if $job.status.conditions -}}
              {{- range $job.status.conditions -}}
                {{- if eq .type "Complete" -}}
                  {{- if eq .status "True" -}}{{$complete = true}}{{- end -}}
                {{- else if eq .type "Failed" -}}
                  {{- if eq .status "True" -}}{{$failed = true}}{{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}
          {{- end -}}
        {{- end -}}
        {{- if $complete -}}True{{- else if $failed -}}False{{- else -}}Unknown{{- end -}}
      reason: |
        {{- $job := .resources.validation-job -}}
        {{- $complete := false -}}
        {{- $failed := false -}}
        {{- if $job -}}
          {{- if $job.status -}}
            {{- if $job.status.conditions -}}
              {{- range $job.status.conditions -}}
                {{- if eq .type "Complete" -}}
                  {{- if eq .status "True" -}}{{$complete = true}}{{- end -}}
                {{- else if eq .type "Failed" -}}
                  {{- if eq .status "True" -}}{{$failed = true}}{{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}
          {{- end -}}
        {{- end -}}
        {{- if $complete -}}ValidationPassed{{- else if $failed -}}ValidationFailed{{- else -}}ValidationInProgress{{- end -}}
      message: |
        {{- $job := .resources.validation-job -}}
        {{- $complete := false -}}
        {{- $failed := false -}}
        {{- if $job -}}
          {{- if $job.status -}}
            {{- if $job.status.conditions -}}
              {{- range $job.status.conditions -}}
                {{- if eq .type "Complete" -}}
                  {{- if eq .status "True" -}}{{$complete = true}}{{- end -}}
                {{- else if eq .type "Failed" -}}
                  {{- if eq .status "True" -}}{{$failed = true}}{{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}
          {{- end -}}
        {{- end -}}
        GCP environment validation {{- if $complete -}} passed{{- else if $failed -}} failed{{- else -}} is running{{- end -}}

    - name: "Ready"
      status: |
        {{- $job := .resources.validation-job -}}
        {{- if $job -}}
          {{- if $job.status -}}
            {{- if $job.status.active -}}False{{- else if $job.status.succeeded -}}True{{- else if $job.status.failed -}}False{{- else -}}Unknown{{- end -}}
          {{- else -}}Unknown{{- end -}}
        {{- else -}}False{{- end -}}
      reason: |
        {{- $job := .resources.validation-job -}}
        {{- if $job -}}
          {{- if $job.status -}}
            {{- if $job.status.active -}}JobRunning{{- else if $job.status.succeeded -}}JobSucceeded{{- else if $job.status.failed -}}JobFailed{{- else -}}JobPending{{- end -}}
          {{- else -}}JobPending{{- end -}}
        {{- else -}}JobNotCreated{{- end -}}
      message: |
        {{- $job := .resources.validation-job -}}
        {{- if $job -}}
          {{- if $job.status -}}
            Validation job {{- if $job.status.active -}} is currently running{{- else if $job.status.succeeded -}} completed successfully{{- else if $job.status.failed -}} failed{{- else -}} status is unknown{{- end -}}
          {{- else -}}Validation job status is pending{{- end -}}
        {{- else -}}Validation job not created{{- end -}}